version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - codershouse
    volumes:
      - ./mongo-data:/data/db
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend/
    container_name: backend
    restart: always
    depends_on:
      - mongodb
    ports:
      - "5500:5500"
    volumes:
      - ./backend:/backend
      - ./backend/node_modules
    networks:
      - codershouse
  # frontend:
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./frontend/
  #   container_name: frontend
  #   volumes:
  #     - ./frontend:/frontend
  #     - ./frontend/node_modules
  #   depends_on:
  #     - backend
  #   networks:
  #     - codershouse
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - codershouse

networks:
  codershouse:
    driver: bridge

volumes:
  mongo-data:
    driver: local
