version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend/
    container_name: backend
    restart: always
    ports:
      - "5500:5500"
    volumes:
      - ./backend:/root/backend
    depends_on:
      - mongodb
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/default.conf:/etc/nginx/sites-available/default
      - ./deploy/etc-letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
